# Generated by Django 5.1.3 on 2024-11-26 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dreamer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=20)),
                ("lastname", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Personal", "Personal"),
                            ("Professional", "Professional"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=50)),
                (
                    "dreamer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hopesdreams.dreamer",
                    ),
                ),
            ],
        ),
    ]
