# Generated by Django 5.1.2 on 2024-11-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Rainfall", "Rainfall"),
                            ("Water Level", "Water Level"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Sto. Nino", "Sto. Nino"),
                            ("Boso-Boso", "Boso-Boso"),
                            ("Mt. Aries", "Mt. Aries"),
                            ("Mt. Campana", "Mt. Campana"),
                            ("Mt. Oro", "Mt. Oro"),
                            ("Nangka", "Nangka"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("datetime", models.DateTimeField()),
            ],
        ),
    ]
