# Generated by Django 5.1.2 on 2024-11-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finalsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="value",
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
