# Generated by Django 5.1.2 on 2024-11-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finalsapp", "0002_alter_station_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_station_type",
                    models.CharField(
                        choices=[
                            ("Rainfall", "Rainfall"),
                            ("Water Level", "Water Level"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_station_name",
                    models.CharField(
                        choices=[
                            ("Sto. Nino", "Sto. Nino"),
                            ("Boso-Boso", "Boso-Boso"),
                            ("Mt. Aries", "Mt. Aries"),
                            ("Mt. Campana", "Mt. Campana"),
                            ("Mt. Oro", "Mt. Oro"),
                            ("Nangka", "Nangka"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "datetime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finalsapp.datetime",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Station",
        ),
    ]
